##########################################################################################
# tests/test_docstrings.py: Enforcement of the project docstring standard
##########################################################################################
"""Tests that every function in the package obeys the project docstring standard.

The programs under programs/ are held to it too. They are not packaged, but they generate
the data the package ships, and nothing else checks them.

The standard, recorded in .claude/rules/docstrings.md, is:

* Every function has a Google-style docstring.
* Parameters appear under a "Parameters:" header, never "Args:", "Inputs:", or "Input:".
* Each entry names the parameter and its type or tuple of types, then describes it.
* A parameter defaulting to None is marked "optional".
* A function that can return a value ends with a "Returns:" section; a function that
  cannot has no such section.
* An optional "Raises:" section summarizes each exception.
* No line exceeds 90 columns.

These are structural checks. They cannot tell whether a description is accurate, only
whether it is present and correctly shaped.
"""

import ast
import pathlib

import pytest

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
PACKAGE_ROOT = REPO_ROOT / 'src' / 'spyceman'

# programs/ is not packaged, but it emits the machine-generated KTuple tables and is
# written to the same standard as the package.
PROGRAMS_ROOT = REPO_ROOT / 'programs'

# _version.py is generated by setuptools_scm at build time and is not ours to format.
SOURCE_FILES = sorted([p for p in PACKAGE_ROOT.rglob('*.py') if p.name != '_version.py']
                      + list(PROGRAMS_ROOT.rglob('*.py')))

# Headers that Google-style docstrings use, so that a line ending in ":" is only read as
# a section header when it is one of these.
SECTION_NAMES = frozenset([
    'Parameters', 'Returns', 'Raises', 'Args', 'Inputs', 'Input', 'Return', 'Yields',
    'Attributes', 'Methods', 'Notes', 'Example', 'Examples',
])

# The headers the standard forbids in favor of "Parameters:".
BANNED_SECTION_NAMES = ('Args', 'Inputs', 'Input', 'Return')

MAX_WIDTH = 90


def _iter_functions(tree):
    """Every function and method defined anywhere in a module, nested ones included.

    Parameters:
        tree (ast.Module): The parsed module.

    Returns:
        list[ast.FunctionDef]: Each function definition found, in source order.
    """

    return [node for node in ast.walk(tree)
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))]


def _returns_a_value(func):
    """Whether this function can return a value or yield one.

    Nested functions and lambdas are not descended into: a `return` inside a closure
    belongs to the closure, not to the function that defines it.

    Parameters:
        func (ast.FunctionDef): The function to examine.

    Returns:
        bool: True if any return statement carries a value, or the function yields.
    """

    def scan(node):
        for child in ast.iter_child_nodes(node):
            if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef, ast.Lambda)):
                continue
            if isinstance(child, ast.Return) and child.value is not None:
                return True
            if isinstance(child, (ast.Yield, ast.YieldFrom)):
                return True
            if scan(child):
                return True
        return False

    return scan(func)


def _declared_params(func):
    """The parameter names in a function's signature, excluding self and cls.

    Parameters:
        func (ast.FunctionDef): The function to examine.

    Returns:
        list[str]: The parameter names, with "*" or "**" prefixed to the variadic ones.
    """

    args = func.args
    names = [p.arg for p in (*args.posonlyargs, *args.args, *args.kwonlyargs)]
    names = [n for n in names if n not in ('self', 'cls')]
    if args.vararg:
        names.append('*' + args.vararg.arg)
    if args.kwarg:
        names.append('**' + args.kwarg.arg)
    return names


def _none_default_params(func):
    """The parameter names whose default value is the literal None.

    Parameters:
        func (ast.FunctionDef): The function to examine.

    Returns:
        list[str]: The names of the parameters defaulting to None.
    """

    args = func.args
    names = []
    positional = [*args.posonlyargs, *args.args]
    defaulted = positional[len(positional) - len(args.defaults):]
    for arg, default in zip(defaulted, args.defaults):
        if isinstance(default, ast.Constant) and default.value is None:
            names.append(arg.arg)
    for arg, default in zip(args.kwonlyargs, args.kw_defaults):
        if isinstance(default, ast.Constant) and default.value is None:
            names.append(arg.arg)
    return names


def _parse_sections(doc):
    """Split a docstring into its Google-style sections.

    Parameters:
        doc (str): The raw docstring, with indentation intact.

    Returns:
        dict[str, list[str]]: Each section header found, mapped to its body lines.
    """

    sections = {}
    current = None
    for line in doc.split('\n'):
        stripped = line.strip()
        if stripped.endswith(':') and stripped[:-1] in SECTION_NAMES:
            current = stripped[:-1]
            sections[current] = []
        elif current is not None:
            sections[current].append(line)
    return sections


def _documented_params(section_lines):
    """The parameter names named at the top level of a "Parameters:" section.

    Only the least-indented lines are entry lines; anything indented further is the
    continuation of the entry above it.

    Parameters:
        section_lines (list[str]): The body lines of a "Parameters:" section.

    Returns:
        list[str]: The parameter names documented there, in order.
    """

    names = []
    base_indent = None
    for line in section_lines:
        if not line.strip():
            continue
        indent = len(line) - len(line.lstrip())
        if base_indent is None:
            base_indent = indent
        if indent != base_indent:
            continue
        head = line.strip().split('(')[0].split(':')[0].strip()
        if head:
            names.append(head)
    return names


def _check_function(rel, func):
    """Apply the docstring standard to one function.

    Parameters:
        rel (str): Path to the source file, relative to the package root.
        func (ast.FunctionDef): The function to check.

    Returns:
        list[str]: One message per violation; empty if the function conforms.
    """

    where = f'{rel}:{func.lineno}: {func.name}()'
    problems = []

    doc = ast.get_docstring(func, clean=False)
    if not doc:
        return [f'{where}: no docstring']

    sections = _parse_sections(doc)

    for banned in BANNED_SECTION_NAMES:
        if banned in sections:
            problems.append(f'{where}: uses "{banned}:" instead of "Parameters:"')

    params = _declared_params(func)
    if params:
        if 'Parameters' not in sections:
            problems.append(f'{where}: missing "Parameters:" for {params}')
        else:
            documented = _documented_params(sections['Parameters'])
            for name in params:
                if name not in documented:
                    problems.append(f'{where}: parameter {name!r} is not documented')
            for name in documented:
                if name not in params:
                    problems.append(f'{where}: documents unknown parameter {name!r}')
    elif 'Parameters' in sections:
        problems.append(f'{where}: has "Parameters:" but takes no parameters')

    # Match only the entry line itself: the name must be followed by " (" or ":", so a
    # continuation line starting with a similar word is not read as the entry.
    for name in _none_default_params(func):
        for line in sections.get('Parameters', []):
            stripped = line.strip()
            if stripped.startswith(name + ' (') or stripped.startswith(name + ':'):
                if 'optional' not in line:
                    problems.append(f'{where}: parameter {name!r} defaults to None but '
                                    'is not marked "optional"')
                break

    wants_return = _returns_a_value(func)
    has_return = 'Returns' in sections
    if wants_return and not has_return:
        problems.append(f'{where}: returns a value but has no "Returns:" section')
    if has_return and not wants_return:
        problems.append(f'{where}: has "Returns:" but never returns a value')

    if 'xxx' in doc or 'Xxx' in doc:
        problems.append(f'{where}: still contains an "xxx" placeholder')

    return problems


@pytest.mark.parametrize('path', SOURCE_FILES,
                         ids=lambda p: str(p.relative_to(REPO_ROOT)))
def test_docstrings_follow_the_standard(path):
    """Every function in the file has a conforming docstring.

    Parameters:
        path (pathlib.Path): Path to the module to check.
    """

    rel = str(path.relative_to(REPO_ROOT))
    tree = ast.parse(path.read_text(encoding='utf-8'), str(path))

    problems = []
    for func in _iter_functions(tree):
        problems += _check_function(rel, func)

    assert not problems, '\n'.join(problems)


@pytest.mark.parametrize('path', SOURCE_FILES,
                         ids=lambda p: str(p.relative_to(REPO_ROOT)))
def test_lines_are_not_too_wide(path):
    """No line in the file exceeds the 90-column limit.

    Parameters:
        path (pathlib.Path): Path to the module to check.
    """

    rel = str(path.relative_to(REPO_ROOT))
    wide = [f'{rel}:{n}: {len(line)} columns'
            for n, line in enumerate(path.read_text(encoding='utf-8').split('\n'), 1)
            if len(line) > MAX_WIDTH]

    assert not wide, '\n'.join(wide)

##########################################################################################
